from app.llm import analyze_and_generate, compose_answer
from app.validator import validate_query, QueryValidationError
from app.db import execute_query
from app.visuals import suggest_viz


class PipelineError(Exception):
    def __init__(self, stage: str, message: str):
        self.stage = stage
        self.message = message
        super().__init__(f"[{stage}] {message}")


def run_pipeline(question: str, history: list = [], context: dict = None) -> dict:
    plan = analyze_and_generate(question, history, context)
    intent = plan["intent"]
    params = plan["parameters"]

    # --- DIRECT ANSWER (no DB needed) ---
    if intent == "answer_directly":
        return {
            "question": question,
            "answer": params.get("answer", ""),
            "data": None,
            "sql": None,
            "row_count": None,
            "suggested_viz": None,
            "chart_config": None,
        }

    # --- CLARIFICATION ---
    if intent == "clarify":
        return {
            "question": question,
            "answer": params.get("question", ""),
            "data": None,
            "sql": None,
            "row_count": None,
            "suggested_viz": None,
            "chart_config": None,
        }

    # --- DATABASE QUERY ---
    if intent == "query_database":
        # DEBUG: Log the raw SQL generated by LLM
        print(f"DEBUG: Executing SQL -> {params['sql']}") 
        
        results = execute_query(validate_query(params['sql']))
        answer = compose_answer(question, results, history)
        viz = suggest_viz(results)

        return {
            "question": question,
            "answer": answer,
            "data": results,
            "sql": params['sql'],
            "row_count": len(results),
            "chart_config": viz # Single source of truth for UI
        }

    # Fallback — should not reach here
    raise PipelineError("pipeline", f"Unknown intent: {intent}")